// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkvdGw8Q1_8bsMHJf4juofHNSbKR5UZc',
    appId: '1:728192242235:web:6b405064e1d790abc3021e',
    messagingSenderId: '728192242235',
    projectId: 'tappo-8a692',
    authDomain: 'tappo-8a692.firebaseapp.com',
    storageBucket: 'tappo-8a692.firebasestorage.app',
    measurementId: 'G-LFPL64JGWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWraH_PbxnYOxYCc1xnZtDcud04hlpvfg',
    appId: '1:728192242235:android:0cc920bcf517bf60c3021e',
    messagingSenderId: '728192242235',
    projectId: 'tappo-8a692',
    storageBucket: 'tappo-8a692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPzizgy3BuYnSLyHxe2QhfmRLKIQPaZE',
    appId: '1:728192242235:ios:7635b430702d0ebac3021e',
    messagingSenderId: '728192242235',
    projectId: 'tappo-8a692',
    storageBucket: 'tappo-8a692.firebasestorage.app',
    iosBundleId: 'com.example.tappo',
  );
}
